sonar.projectKey=frontend-vitamia
sonar.projectName=frontend-vitamia
sonar.projectVersion=1.0
sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/public/**,**/*.test.tsx,**/*.spec.tsx,**/__tests__/**,**/mocks/**,**/index.css,**/types/**,**/api/**,**/hooks/**,**/context/**,**/pages/**,**/router/AppRouter.tsx,**/components/forms/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_a32a913989f55dfe3a74ca4ca7429b165e000679